# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charasite', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of your team', max_length=200)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the project', max_length=1000, null=True)),
                ('is_public', models.BooleanField(help_text='Do you want the project to be referenced ?')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of your new repository', max_length=200)),
                ('parent_repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charasite.Repository')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('o', 'Owner'), ('a', 'Administrator'), ('m', 'Moderator'), ('w', 'Writer'), ('t', 'Translator'), ('r', 'Reader')], default='a', help_text='Define the level of authorisation for the User', max_length=1)),
                ('date_join', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Project')),
            ],
        ),
    ]
