# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charasite', '0003_project_repository_teammembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Number of the chapter')),
                ('title', models.CharField(help_text='Enter the title of this chapter', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief summary for this chapter', max_length=1000, null=True)),
                ('chapter', models.TextField(blank=True, help_text='Your chapter', max_length=200000, null=True)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_last_edit', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Number of the chapter')),
                ('begin', models.IntegerField(help_text='first chap')),
                ('end', models.IntegerField(help_text='last chap')),
                ('title', models.CharField(help_text='Enter the title of this volume', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='charasite.Genre'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Project'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Project'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Repository'),
        ),
    ]
