# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charasite', '0004_auto_20170925_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['number']},
        ),
    ]
