# Generated by Django 2.0a1 on 2017-10-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charasite', '0005_auto_20170927_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chapter',
            name='prevChapter',
            field=models.ForeignKey(blank=True, help_text='The previous chapter', null=True, on_delete=django.db.models.deletion.SET_NULL, to='charasite.Chapter'),
        ),
    ]
