# Generated by Django 2.0a1 on 2017-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charasite', '0006_auto_20171014_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date_of_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
