# Generated by Django 2.0a1 on 2017-10-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charasite', '0007_auto_20171016_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of this article', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief summary for this article', max_length=1000, null=True)),
                ('content', models.TextField(blank=True, help_text='Your article', max_length=200000, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_edit', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('prevArticle', models.ForeignKey(blank=True, help_text='The previous article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='charasite.Article')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_last_edit'],
            },
        ),
    ]
