# Generated by Django 2.0a1 on 2017-10-28 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charasite', '0008_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Write a comment !', max_length=1000, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_edit', models.DateTimeField(auto_now=True)),
                ('nb_upvote', models.IntegerField(default=0)),
                ('nb_downvote', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Write a comment !', max_length=1000, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_edit', models.DateTimeField(auto_now=True)),
                ('nb_upvote', models.IntegerField(default=0)),
                ('nb_downvote', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='CommentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Write a comment !', max_length=1000, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_edit', models.DateTimeField(auto_now=True)),
                ('nb_upvote', models.IntegerField(default=0)),
                ('nb_downvote', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Article')),
            ],
        ),
    ]
