# Generated by Django 2.0a1 on 2017-10-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charasite', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charasite.Project'),
        ),
    ]
